# Generated by Django 6.0.6 on 2026-06-28 22:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='collages/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_prompt', models.TextField()),
                ('parsed_intent', models.JSONField(help_text='NLP extracted intent (target_image, actions)')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error')], default='SUCCESS', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel_index', models.PositiveIntegerField(help_text='Sequential index of the panel')),
                ('x_coord', models.PositiveIntegerField()),
                ('y_coord', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('header_height', models.PositiveIntegerField(default=0, help_text='Height of the text area')),
                ('has_borders', models.BooleanField(default=False)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='extractor.collage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('raw_text', models.TextField(help_text='Full text dumped from OCR')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('panel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_data', to='extractor.panel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_image', models.ImageField(upload_to='outputs/%Y/%m/%d/')),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('applied_operations', models.JSONField(help_text='List of ops: crop, inpaint, upscale, etc.')),
                ('source_panel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.panel')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='extractor.prompthistory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='extractor.session'),
        ),
        migrations.AddField(
            model_name='collage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collages', to='extractor.session'),
        ),
    ]
